apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: "sparkjob"
spec:
  schedule: "*/3 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobspark"
        spec:
          containers:
          - env:
            - name: OSHINKO_CLUSTER_NAME
              value: instance
            - name: APP_ARGS
            - name: SPARK_OPTIONS
            - name: APP_MAIN_CLASS
              value: com.barclays.fraud.freature.schedule.MainApp
            - name: OSHINKO_DEL_CLUSTER
              value: 'true'
            - name: APP_EXIT
              value: 'true'
            - name: OSHINKO_NAMED_CONFIG
            - name: OSHINKO_SPARK_DRIVER_CONFIG
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            name: "spark"
            volumeMounts:
              - mountPath: /etc/podinfo
                name: podinfo
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: oshinko-token-63zbg
                readOnly: true
            image: "172.30.1.1:5000/test/fraud-feature-java-schedule"
          restartPolicy: Never
          serviceAccount: oshinko
          serviceAccountName: oshinko
          terminationGracePeriodSeconds: 30
          volumes:
            - downwardAPI:
                defaultMode: 420
                items:
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.labels
                    path: labels
              metadata:
                defaultMode: 420
                items:
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.labels
                    name: labels
              name: podinfo
            - name: oshinko-token-63zbg
              secret:
                defaultMode: 420
                secretName: oshinko-token-63zbg
